name: aws-profile-extension
description: "Easy AWS profile switching with SSO support and tab completion"
author: "Luka Matovic"
version: "1.0.0"
website: "https://github.com/ml170722d/aws-profile-extension"
dependencies:
  - git
  - python3
